from __future__ import annotations

from datetime import datetime
from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class MemoryStoreInterface(Protocol):
    def add(self,run_id:str,kind:str,content:str,metadata:dict[str,Any]|None=None)->int: ...
    def search(self,query:str,limit:int=8)->list[dict[str,Any]]: ...
    def recent(self,limit:int=20)->list[dict[str,Any]]: ...
@runtime_checkable
class JobStoreInterface(Protocol):
    def enqueue(self,goal:str,run_at:datetime|None=None,max_attempts:int=3)->str: ...
    def claim(self)->dict[str,Any]|None: ...
    def finish(self,ident:str,result:dict[str,Any],lease_token:str|None=None)->None: ...
    def fail(self,ident:str,error:str,lease_token:str|None=None)->None: ...
    def request_cancel(self,ident:str)->str|None: ...
    def get(self,ident:str)->dict[str,Any]|None: ...
@runtime_checkable
class PlanStoreInterface(Protocol):
    def create(self,plan:Any)->dict[str,Any]: ...
    def get(self,ident:str)->dict[str,Any]: ...
    def replace(self,ident:str,plan:Any,expected_version:int,reason:str)->dict[str,Any]: ...
    def history(self,ident:str)->list[dict[str,Any]]: ...
@runtime_checkable
class TokenStoreInterface(Protocol):
    def create(self,name:str,scopes:set[str],expires_at:str|None=None)->tuple[str,str]: ...
    def authenticate(self,token:str)->Any|None: ...
    def revoke(self,ident:str)->bool: ...
@runtime_checkable
class AuditStoreInterface(Protocol):
    def append(self,actor:str,action:str,resource:str,outcome:str,metadata:dict[str,Any]|None=None)->int: ...
    def verify(self)->tuple[bool,int|None]: ...
    def list(self,after:int=0,limit:int=100)->list[dict[str,Any]]: ...
@runtime_checkable
class MigrationStoreInterface(Protocol):
    def pending(self)->list[int]: ...
    def apply(self,target:int|None=None)->list[int]: ...
