from __future__ import annotations

from datetime import datetime
from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class MemoryStoreInterface(Protocol):
    def add(self,run_id:str,kind:str,content:str,metadata:dict[str,Any]|None=None)->int: ...
    def search(self,query:str,limit:int=8)->list[dict[str,Any]]: ...
    def recent(self,limit:int=20)->list[dict[str,Any]]: ...
@runtime_checkable
class JobStoreInterface(Protocol):
    def enqueue(self,goal:str,run_at:datetime|None=None,max_attempts:int=3)->str: ...
    def claim(self)->dict[str,Any]|None: ...
    def finish(self,ident:str,result:dict[str,Any],lease_token:str|None=None)->None: ...
    def fail(self,ident:str,error:str,lease_token:str|None=None)->None: ...
    def request_cancel(self,ident:str)->str|None: ...
    def get(self,ident:str)->dict[str,Any]|None: ...
@runtime_checkable
class PlanStoreInterface(Protocol):
    def create(self,plan:Any)->dict[str,Any]: ...
    def get(self,ident:str)->dict[str,Any]: ...
    def replace(self,ident:str,plan:Any,expected_version:int,reason:str)->dict[str,Any]: ...
    def history(self,ident:str)->list[dict[str,Any]]: ...
@runtime_checkable
class TokenStoreInterface(Protocol):
    def create(self,name:str,scopes:set[str],expires_at:str|None=None,owner_id:str|None=None,token_kind:str="api")->tuple[str,str]: ...
    def authenticate(self,token:str)->Any|None: ...
    def introspect(self,token:str)->dict[str,Any]|None: ...
    def list_metadata(self,revoked:bool|None=None,before:str|None=None,limit:int=100,cursor:str|None=None,owner_id:str|None=None,token_kind:str|None=None)->tuple[list[dict[str,Any]],str|None]: ...
    def revoke(self,ident:str,owner_id:str|None=None)->bool: ...
    def create_account(self,email:str,password:str,display_name:str)->tuple[dict[str,Any],str]: ...
    def login_account(self,email:str,password:str)->tuple[dict[str,Any],str]|None: ...
    def account_by_email(self,email:str)->dict[str,Any]|None: ...
    def get_account(self,account_id:str)->dict[str,Any]|None: ...
    def reset_password(self,account_id:str,password:str)->bool: ...
    def disable_account(self,account_id:str)->bool: ...
    def ping(self)->bool: ...
@runtime_checkable
class AuditStoreInterface(Protocol):
    def append(self,actor:str,action:str,resource:str,outcome:str,metadata:dict[str,Any]|None=None)->int: ...
    def verify(self)->tuple[bool,int|None]: ...
    def list(self,after:int=0,limit:int=100)->list[dict[str,Any]]: ...
    def list_page(self,after:int=0,limit:int=100)->tuple[list[dict[str,Any]],str|None]: ...
    def ping(self)->bool: ...
@runtime_checkable
class EmailVerificationStoreInterface(Protocol):
    def issue(self,account_id:str,ttl_minutes:int=30)->str: ...
    def verify(self,account_id:str,raw:str)->bool: ...
    def status(self,account_id:str)->bool: ...
    def issue_password_reset(self,account_id:str,ttl_minutes:int=20)->str: ...
    def consume_password_reset(self,account_id:str,raw:str)->bool: ...
    def ping(self)->bool: ...
@runtime_checkable
class QuotaStoreInterface(Protocol):
    def limit(self,principal:str)->int: ...
    def set_limit(self,principal:str,daily_jobs:int)->None: ...
    def consume_job(self,principal:str,now:datetime|None=None)->dict[str,int|str]: ...
    def status(self,principal:str,now:datetime|None=None)->dict[str,int|str]: ...
    def delete_principal(self,principal:str)->dict[str,int]: ...
    def ping(self)->bool: ...
@runtime_checkable
class EntitlementStoreInterface(Protocol):
    def plan_name(self,principal:str)->str: ...
    def get(self,principal:str)->dict: ...
    def assign(self,principal:str,plan:str,updated_at:str)->dict: ...
    def allows(self,principal:str,resource:str,current:int)->bool: ...
    def delete_principal(self,principal:str)->int: ...
    def ping(self)->bool: ...
@runtime_checkable
class RunStoreInterface(Protocol):
    def add(self,principal:str,report:Any)->None: ...
    def get(self,principal:str,run_id:str)->dict|None: ...
    def list(self,principal:str,before:str|None=None,limit:int=100,cursor:str|None=None)->tuple[list[dict],str|None]: ...
    def run_ids(self,principal:str)->list[str]: ...
    def delete_principal(self,principal:str)->int: ...
    def ping(self)->bool: ...
@runtime_checkable
class IdempotencyStoreInterface(Protocol):
    def get(self,principal:str,route:str,key:str,payload:Any)->tuple[int,Any]|None: ...
    def put(self,principal:str,route:str,key:str,payload:Any,status:int,response:Any)->None: ...
    def claim(self,principal:str,route:str,key:str,payload:Any)->tuple[int,Any]|None: ...
    def release(self,principal:str,route:str,key:str)->None: ...
    def delete_principal(self,principal:str)->int: ...
    def ping(self)->bool: ...
@runtime_checkable
class WebhookStoreInterface(Protocol):
    def subscribe(self,principal:str,url:str,events:set[str],fields:set[str]|None=None,headers:dict[str,str]|None=None)->tuple[str,str]: ...
    def unsubscribe(self,ident:str,principal:str)->bool: ...
    def enqueue(self,event_id:str,event_type:str,payload:dict,*,principal:str)->int: ...
    def claim(self,now:float|None=None)->dict|None: ...
    def succeed(self,ident:str,status:int)->None: ...
    def retry(self,ident:str,error:str,max_attempts:int=8)->None: ...
    def recover_stale(self,stale_before:float)->int: ...
    def set_active(self,ident:str,principal:str,active:bool,cooldown_seconds:int=0)->bool: ...
    def attempt_timeline(self,delivery_id:str,principal:str)->list[dict]: ...
    def health(self,ident:str,principal:str)->dict|None: ...
    def rotate_secret(self,ident:str,principal:str)->str|None: ...
    def active_count(self,principal:str)->int: ...
    def list_subscriptions(self,principal:str,limit:int=100,cursor:str|None=None)->tuple[list[dict],str|None]: ...
    def enqueue_test(self,ident:str,principal:str)->str|None: ...
    def delivery_metrics(self)->dict[str,int]: ...
    def list_deliveries(self,principal:str,status:str|None=None,after:str|None=None,limit:int=100,cursor:str|None=None)->tuple[list[dict],str|None]: ...
    def get_delivery(self,principal:str,delivery_id:str)->dict|None: ...
    def replay_delivery(self,principal:str,delivery_id:str)->bool: ...
    def cleanup_deliveries(self,delivered_before:str,failed_before:str)->dict[str,int]: ...
    def operational_metrics(self)->dict[str,float]: ...
    def delete_principal(self,principal:str)->dict[str,int]: ...
    def ping(self)->bool: ...
@runtime_checkable
class CompanionStoreInterface(Protocol):
    def upsert_user(self,profile:Any)->dict[str,Any]: ...
    def get_user(self,user_id:str)->dict[str,Any]|None: ...
    def profile(self,user_id:str)->Any: ...
    def list_users(self,limit:int=100)->list[dict[str,Any]]: ...
    def add_fact(self,user_id:str,fact:Any,source:str)->dict[str,Any]: ...
    def get_fact(self,fact_id:int)->dict[str,Any]|None: ...
    def list_facts(self,user_id:str,active_only:bool=True,limit:int=200)->list[dict[str,Any]]: ...
    def supersede_fact(self,fact_id:int,replacement_id:int|None=None)->bool: ...
    def find_fact_text(self,user_id:str,text:str)->dict[str,Any]|None: ...
    def search_facts(self,user_id:str,query:str,limit:int=8)->list[dict[str,Any]]: ...
    def start_conversation(self,user_id:str,channel:str,conversation_id:str|None=None)->dict[str,Any]: ...
    def get_conversation(self,conversation_id:str)->dict[str,Any]|None: ...
    def latest_conversation(self,user_id:str,channel:str)->dict[str,Any]|None: ...
    def list_conversations(self,user_id:str,limit:int=50)->list[dict[str,Any]]: ...
    def add_message(self,conversation_id:str,role:str,content:str)->dict[str,Any]: ...
    def history(self,conversation_id:str,limit:int=40)->list[dict[str,Any]]: ...
    def schedule_checkin(self,user_id:str,due_at:datetime,slot:str,channel:str,address:str|None,max_attempts:int=3)->tuple[dict[str,Any],bool]: ...
    def claim_checkin(self,now:datetime|None=None)->dict[str,Any]|None: ...
    def finish_checkin(self,checkin_id:str,message:str)->None: ...
    def fail_checkin(self,checkin_id:str,error:str)->str: ...
    def cancel_pending_checkins(self,user_id:str)->int: ...
    def list_checkins(self,user_id:str,status:str|None=None,limit:int=50)->list[dict[str,Any]]: ...
    def record_model_trace(self,message_id:int,conversation_id:str,trace:dict[str,Any])->None: ...
    def model_traces(self,conversation_id:str,limit:int=100)->list[dict[str,Any]]: ...
    def export_user_data(self,user_id:str)->dict[str,Any]: ...
    def delete_user_data(self,user_id:str)->dict[str,int]: ...
    def ping(self)->bool: ...
@runtime_checkable
class MigrationStoreInterface(Protocol):
    def pending(self)->list[int]: ...
    def apply(self,target:int|None=None)->list[int]: ...
@runtime_checkable
class ApprovalStoreInterface(Protocol):
    def grant(self,principal:str,tool:str,granted_by:str,expires_at:str|None=None,argument_constraints:dict|None=None)->None: ...
    def allows(self,principal:str,tool:str,now:datetime|None=None,arguments:dict|None=None)->bool: ...
    def revoke(self,principal:str,tool:str)->bool: ...
    def active_count(self,principal:str,now:datetime|None=None)->int: ...
    def list(self,principal:str)->list[dict[str,Any]]: ...
    def delete_principal(self,principal:str)->int: ...


@runtime_checkable
class PersonalModelStoreInterface(Protocol):
    def upsert(self,owner_id:str,item:Any)->dict: ...
    def get(self,owner_id:str,ident:str)->dict|None: ...
    def list(self,owner_id:str,kind:Any=None,include_history:bool=False)->list[dict]: ...
    def correct(self,owner_id:str,ident:str,value:str)->dict|None: ...
    def decay(self,owner_id:str,before:str,factor:float=0.9)->int: ...
    def delete(self,owner_id:str,ident:str)->bool: ...
    def context(self,owner_id:str)->str: ...
    def expire(self,owner_id:str,at:str|None=None)->int: ...
    def purge_owner(self,owner_id:str)->dict[str,int]: ...


@runtime_checkable
class ContextStoreInterface(Protocol):
    def register_source(self,owner_id:str,source_id:str,connector:str,config:dict,permission:Any="private")->dict: ...
    def source(self,owner_id:str,source_id:str)->dict|None: ...
    def cursor(self,owner_id:str,source_id:str)->str|None: ...
    def ingest(self,record:Any)->bool: ...
    def search(self,owner_id:str,query:str,limit:int=12,allowed:set[str]|None=None)->list[dict]: ...
    def owner_watermarks(self)->dict[str,int]: ...
    def recent(self,owner_id:str,limit:int=12,allowed:set[str]|None=None)->list[dict]: ...
    def assemble(self,owner_id:str,query:str,limit:int=12)->dict: ...
    def purge_owner(self,owner_id:str)->dict[str,int]: ...


@runtime_checkable
class MonitorStoreInterface(Protocol):
    def create(self,owner_id:str,item:Any)->dict: ...
    def get(self,owner_id:str,ident:str)->dict|None: ...
    def list(self,owner_id:str,status:str|None=None)->list[dict]: ...
    def evaluate(self,owner_id:str,source_id:str,event:dict,at:str|None=None)->list[str]: ...
    def cancel(self,owner_id:str,ident:str)->bool: ...
    def events(self,owner_id:str,ident:str)->list[dict]: ...
    def delete_owner(self,owner_id:str)->dict[str,int]: ...


@runtime_checkable
class ReflectionScheduleInterface(Protocol):
    def state(self,owner_id:str)->dict[str,Any]|None: ...
    def due(self,watermarks:dict[str,int],interval:Any,now:Any=None)->list[str]: ...
    def record(self,owner_id:str,status:str,result:dict[str,Any],watermark:int|None,now:Any=None)->None: ...
    def delete_owner(self,owner_id:str)->int: ...


@runtime_checkable
class DeletionLedgerInterface(Protocol):
    def open(self,principal:str,requested_by:str)->str: ...
    def done_steps(self,deletion_id:str)->dict[str,dict]: ...
    def record_step(self,deletion_id:str,step:str,counts:dict)->None: ...
    def complete(self,deletion_id:str)->None: ...
    def get(self,deletion_id:str)->dict|None: ...
    def incomplete(self)->list[dict]: ...
    def deleted_since(self,principal:str,since:str)->bool: ...
