from __future__ import annotations

from datetime import datetime
from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class MemoryStoreInterface(Protocol):
    def add(self,run_id:str,kind:str,content:str,metadata:dict[str,Any]|None=None)->int: ...
    def search(self,query:str,limit:int=8)->list[dict[str,Any]]: ...
    def recent(self,limit:int=20)->list[dict[str,Any]]: ...
@runtime_checkable
class JobStoreInterface(Protocol):
    def enqueue(self,goal:str,run_at:datetime|None=None,max_attempts:int=3)->str: ...
    def claim(self)->dict[str,Any]|None: ...
    def finish(self,ident:str,result:dict[str,Any],lease_token:str|None=None)->None: ...
    def fail(self,ident:str,error:str,lease_token:str|None=None)->None: ...
    def request_cancel(self,ident:str)->str|None: ...
    def get(self,ident:str)->dict[str,Any]|None: ...
@runtime_checkable
class PlanStoreInterface(Protocol):
    def create(self,plan:Any)->dict[str,Any]: ...
    def get(self,ident:str)->dict[str,Any]: ...
    def replace(self,ident:str,plan:Any,expected_version:int,reason:str)->dict[str,Any]: ...
    def history(self,ident:str)->list[dict[str,Any]]: ...
@runtime_checkable
class TokenStoreInterface(Protocol):
    def create(self,name:str,scopes:set[str],expires_at:str|None=None,owner_id:str|None=None,token_kind:str="api")->tuple[str,str]: ...
    def authenticate(self,token:str)->Any|None: ...
    def introspect(self,token:str)->dict[str,Any]|None: ...
    def list_metadata(self,revoked:bool|None=None,before:str|None=None,limit:int=100,cursor:str|None=None,owner_id:str|None=None,token_kind:str|None=None)->tuple[list[dict[str,Any]],str|None]: ...
    def revoke(self,ident:str,owner_id:str|None=None)->bool: ...
    def create_account(self,email:str,password:str,display_name:str)->tuple[dict[str,Any],str]: ...
    def login_account(self,email:str,password:str)->tuple[dict[str,Any],str]|None: ...
    def account_by_email(self,email:str)->dict[str,Any]|None: ...
    def get_account(self,account_id:str)->dict[str,Any]|None: ...
    def reset_password(self,account_id:str,password:str)->bool: ...
    def disable_account(self,account_id:str)->bool: ...
    def ping(self)->bool: ...
@runtime_checkable
class AuditStoreInterface(Protocol):
    def append(self,actor:str,action:str,resource:str,outcome:str,metadata:dict[str,Any]|None=None)->int: ...
    def verify(self)->tuple[bool,int|None]: ...
    def list(self,after:int=0,limit:int=100)->list[dict[str,Any]]: ...
    def list_page(self,after:int=0,limit:int=100)->tuple[list[dict[str,Any]],str|None]: ...
    def ping(self)->bool: ...
@runtime_checkable
class EmailVerificationStoreInterface(Protocol):
    def issue(self,account_id:str,ttl_minutes:int=30)->str: ...
    def verify(self,account_id:str,raw:str)->bool: ...
    def status(self,account_id:str)->bool: ...
    def issue_password_reset(self,account_id:str,ttl_minutes:int=20)->str: ...
    def consume_password_reset(self,account_id:str,raw:str)->bool: ...
    def ping(self)->bool: ...
@runtime_checkable
class QuotaStoreInterface(Protocol):
    def limit(self,principal:str)->int: ...
    def set_limit(self,principal:str,daily_jobs:int)->None: ...
    def consume_job(self,principal:str,now:datetime|None=None)->dict[str,int|str]: ...
    def status(self,principal:str,now:datetime|None=None)->dict[str,int|str]: ...
    def delete_principal(self,principal:str)->dict[str,int]: ...
    def ping(self)->bool: ...
@runtime_checkable
class EntitlementStoreInterface(Protocol):
    def plan_name(self,principal:str)->str: ...
    def get(self,principal:str)->dict: ...
    def assign(self,principal:str,plan:str,updated_at:str)->dict: ...
    def allows(self,principal:str,resource:str,current:int)->bool: ...
    def delete_principal(self,principal:str)->int: ...
    def ping(self)->bool: ...
@runtime_checkable
class MigrationStoreInterface(Protocol):
    def pending(self)->list[int]: ...
    def apply(self,target:int|None=None)->list[int]: ...
@runtime_checkable
class ApprovalStoreInterface(Protocol):
    def grant(self,principal:str,tool:str,granted_by:str,expires_at:str|None=None,argument_constraints:dict|None=None)->None: ...
    def allows(self,principal:str,tool:str,now:datetime|None=None,arguments:dict|None=None)->bool: ...
    def revoke(self,principal:str,tool:str)->bool: ...
    def active_count(self,principal:str,now:datetime|None=None)->int: ...
    def list(self,principal:str)->list[dict[str,Any]]: ...
    def delete_principal(self,principal:str)->int: ...
