-- Companion profiles, facts, conversations, messages, model traces and the check-in queue shared by
-- every API host and companion worker on this database. Same semantics as companion.sqlite3.
-- JSON-bearing columns stay text (persona, checkins, attempts) so exports match SQLite byte for byte.
CREATE TABLE meemee_companion_users (
  user_id text PRIMARY KEY,
  display_name text NOT NULL,
  timezone text NOT NULL,
  persona text NOT NULL,
  checkins text NOT NULL,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);

CREATE TABLE meemee_companion_facts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL,
  category text NOT NULL,
  text text NOT NULL,
  confidence double precision NOT NULL,
  source text NOT NULL,
  superseded_by bigint,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  fts tsvector GENERATED ALWAYS AS (to_tsvector('simple', text)) STORED
);
CREATE INDEX meemee_companion_facts_user ON meemee_companion_facts(user_id, id);
CREATE INDEX meemee_companion_facts_fts ON meemee_companion_facts USING gin(fts);

CREATE TABLE meemee_companion_conversations (
  id text PRIMARY KEY,
  user_id text NOT NULL,
  channel text NOT NULL,
  created_at timestamptz NOT NULL,
  last_message_at timestamptz NOT NULL
);
CREATE INDEX meemee_companion_conversations_user ON meemee_companion_conversations(user_id, channel, last_message_at DESC);

CREATE TABLE meemee_companion_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id text NOT NULL,
  role text NOT NULL CHECK (role IN ('user','assistant','system')),
  content text NOT NULL,
  created_at timestamptz NOT NULL
);
CREATE INDEX meemee_companion_messages_conversation ON meemee_companion_messages(conversation_id, id);

CREATE TABLE meemee_companion_message_models (
  message_id bigint PRIMARY KEY,
  conversation_id text NOT NULL,
  role text,
  profile text,
  model text,
  attempts text NOT NULL,
  created_at timestamptz NOT NULL
);
CREATE INDEX meemee_companion_message_models_conversation ON meemee_companion_message_models(conversation_id, message_id);

CREATE TABLE meemee_companion_checkins (
  id text PRIMARY KEY,
  user_id text NOT NULL,
  slot text NOT NULL,
  due_at timestamptz NOT NULL,
  status text NOT NULL CHECK (status IN ('queued','running','done','failed','cancelled')),
  attempts integer NOT NULL DEFAULT 0,
  max_attempts integer NOT NULL DEFAULT 3,
  channel text NOT NULL,
  address text,
  message text,
  last_error text,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  UNIQUE (user_id, slot)
);
CREATE INDEX meemee_companion_checkins_due ON meemee_companion_checkins(status, due_at);
CREATE INDEX meemee_companion_checkins_user ON meemee_companion_checkins(user_id, due_at DESC);
