-- Personal model and connected context shared by every API host, agent worker and reflection
-- scheduler on this database. Same semantics as personal-model.sqlite3 and context.sqlite3.
-- Time and JSON columns stay text: the stores compare ISO strings (decay, expiry) and connectors
-- supply occurred_at verbatim, so values and exports match SQLite exactly.
CREATE TABLE meemee_personal_items (
  id text PRIMARY KEY,
  owner_id text NOT NULL,
  kind text NOT NULL,
  title text NOT NULL,
  value text NOT NULL,
  confidence double precision NOT NULL,
  status text NOT NULL CHECK (status IN ('active','superseded','deleted')),
  valid_from text,
  valid_until text,
  supersedes_id text,
  created_at text NOT NULL,
  updated_at text NOT NULL
);
-- Only one active claim per (owner, kind, title); history rows may repeat.
CREATE UNIQUE INDEX meemee_personal_items_active ON meemee_personal_items(owner_id, kind, title) WHERE status = 'active';
CREATE INDEX meemee_personal_owner_kind ON meemee_personal_items(owner_id, kind, status, updated_at DESC);

CREATE TABLE meemee_personal_evidence (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id text NOT NULL REFERENCES meemee_personal_items(id),
  owner_id text NOT NULL,
  source_id text NOT NULL,
  source_record_id text NOT NULL,
  observed_value text NOT NULL,
  confidence double precision NOT NULL,
  observed_at text NOT NULL,
  UNIQUE (item_id, source_id, source_record_id, observed_value)
);
CREATE INDEX meemee_personal_evidence_item ON meemee_personal_evidence(owner_id, item_id, observed_at DESC);

CREATE TABLE meemee_context_sources (
  owner_id text NOT NULL,
  source_id text NOT NULL,
  connector text NOT NULL,
  config text NOT NULL,
  permission text NOT NULL,
  cursor text,
  created_at text NOT NULL,
  updated_at text NOT NULL,
  PRIMARY KEY (owner_id, source_id)
);

CREATE TABLE meemee_context_records (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id text NOT NULL,
  source_id text NOT NULL,
  external_id text NOT NULL,
  content_hash text NOT NULL,
  kind text NOT NULL,
  title text NOT NULL,
  content text NOT NULL,
  occurred_at text NOT NULL,
  provenance text NOT NULL,
  visibility text NOT NULL,
  cursor text,
  metadata text NOT NULL,
  ingested_at text NOT NULL,
  fts tsvector GENERATED ALWAYS AS (to_tsvector('simple', title || ' ' || content)) STORED,
  UNIQUE (owner_id, source_id, external_id, content_hash)
);
CREATE INDEX meemee_context_owner_time ON meemee_context_records(owner_id, occurred_at DESC, id DESC);
CREATE INDEX meemee_context_fts ON meemee_context_records USING gin(fts);
