-- Monitors, their event history and the scheduled-reflection watermarks, shared by every API host
-- and reflection worker on this database. Same semantics as monitors.sqlite3 and
-- reflection-schedule.sqlite3; time and JSON columns stay text, as in SQLite.
CREATE TABLE meemee_monitors (
  id text PRIMARY KEY,
  owner_id text NOT NULL,
  name text NOT NULL,
  source_id text NOT NULL,
  predicate text NOT NULL,
  deadline text,
  max_fires integer NOT NULL,
  fire_count integer NOT NULL DEFAULT 0,
  status text NOT NULL,
  created_at text NOT NULL,
  updated_at text NOT NULL
);
CREATE INDEX meemee_monitors_owner_status ON meemee_monitors(owner_id, status, deadline);

CREATE TABLE meemee_monitor_events (
  sequence bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  monitor_id text NOT NULL,
  owner_id text NOT NULL,
  kind text NOT NULL,
  payload text NOT NULL,
  created_at text NOT NULL
);
CREATE INDEX meemee_monitor_events_item ON meemee_monitor_events(owner_id, monitor_id, sequence);

CREATE TABLE meemee_reflection_runs (
  owner_id text PRIMARY KEY,
  watermark bigint NOT NULL DEFAULT 0,
  last_attempt_at text,
  last_success_at text,
  last_status text,
  last_result text
);
