-- Browser session records, takeovers, events and takeover notices shared by every API host.
-- The live Chromium session stays in one host's process; host_id records which host holds it, so a
-- restarting host marks only its own sessions lost and other hosts can say where a session lives.
-- Time and JSON columns stay text, as in SQLite; token digests are bytea.
CREATE TABLE meemee_browser_sessions (
  id text PRIMARY KEY,
  owner_id text NOT NULL,
  state text NOT NULL,
  profile text,
  allowed_domains text NOT NULL,
  url text,
  title text,
  created_at text NOT NULL,
  updated_at text NOT NULL,
  closed_at text,
  close_reason text,
  host_id text
);
CREATE INDEX meemee_browser_sessions_owner ON meemee_browser_sessions(owner_id, created_at DESC);
CREATE INDEX meemee_browser_sessions_host ON meemee_browser_sessions(host_id, state);

CREATE TABLE meemee_browser_takeovers (
  id text PRIMARY KEY,
  session_id text NOT NULL REFERENCES meemee_browser_sessions(id),
  token_digest bytea NOT NULL,
  reason text NOT NULL,
  requested_by text NOT NULL,
  created_at text NOT NULL,
  expires_at text NOT NULL,
  claimed_at text,
  finished_at text,
  outcome text,
  note text
);
CREATE INDEX meemee_browser_takeovers_session ON meemee_browser_takeovers(session_id);

CREATE TABLE meemee_browser_session_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id text NOT NULL,
  ts text NOT NULL,
  actor text NOT NULL,
  kind text NOT NULL,
  detail text NOT NULL
);
CREATE INDEX meemee_browser_events_session ON meemee_browser_session_events(session_id, id);

CREATE TABLE meemee_browser_takeover_notices (
  id text PRIMARY KEY,
  takeover_id text NOT NULL UNIQUE,
  session_id text NOT NULL,
  user_id text NOT NULL,
  text text,
  status text NOT NULL CHECK (status IN ('queued','delivered','failed','cancelled')),
  attempts integer NOT NULL DEFAULT 0,
  channel text,
  detail text,
  created_at text NOT NULL,
  updated_at text NOT NULL,
  lease_until text
);
CREATE INDEX meemee_browser_notices_status ON meemee_browser_takeover_notices(status, created_at);
