import { ApiError, AuthenticationError, BadRequestError, ConflictError, IdempotencyConflictError, NetworkError, NotFoundError, PermissionDeniedError, RateLimitError, ServerError, StreamError, ValidationError, WaitTimeoutError } from "./errors.js";
import type { AuthProvider } from "./auth.js"; import { TokenAuth } from "./auth.js"; import { RetryPolicy } from "./retry.js"; import { SSEParser } from "./sse.js";
import { TERMINAL_EVENT_KINDS, TERMINAL_JOB_STATUSES } from "./types.js"; import type { AuditPage, CreatedJob, CreatedToken, HealthStatus, Job, JobCancelResult, JobEvent, Quota, ReadinessStatus, ResponseInfo, RevokedToken, RunReport } from "./types.js";
type Fetch=typeof globalThis.fetch; type RequestOptions={params?:Record<string,string|number>;body?:unknown;headers?:Record<string,string>;signal?:AbortSignal;idempotencyKey?:string};
export interface ClientOptions { auth?:AuthProvider|string; fetch?:Fetch; retry?:RetryPolicy; sleep?:(ms:number)=>Promise<void>; userAgent?:string }
export class MeemeeClient {
 readonly runs:RunsResource;readonly jobs:JobsResource;readonly tokens:TokensResource;readonly audit:AuditResource; lastResponseInfo?:ResponseInfo;
 private readonly fetcher:Fetch;private readonly auth?:AuthProvider;private readonly retry:RetryPolicy;private readonly sleep:(ms:number)=>Promise<void>;
 constructor(private readonly baseUrl:string,options:ClientOptions={}){if(!/^https?:\/\//.test(baseUrl))throw new TypeError("baseUrl must be an absolute http(s) URL");this.baseUrl=baseUrl.replace(/\/$/,"");this.fetcher=options.fetch??globalThis.fetch;this.auth=typeof options.auth==="string"?new TokenAuth(options.auth):options.auth;this.retry=options.retry??new RetryPolicy();this.sleep=options.sleep??(ms=>new Promise(r=>setTimeout(r,ms)));this.runs=new RunsResource(this);this.jobs=new JobsResource(this);this.tokens=new TokensResource(this);this.audit=new AuditResource(this)}
 health(){return this.json<HealthStatus>("GET","/health")} ready(){return this.json<ReadinessStatus>("GET","/ready")} quota(){return this.json<Quota>("GET","/v1/quota")} async metrics(){return (await this.request("GET","/metrics")).text()}
 async request(method:string,path:string,o:RequestOptions={}):Promise<Response>{let attempt=0;for(;;){attempt++;const headers:{[k:string]:string}={Accept:"application/json",...o.headers};if(this.auth)headers.Authorization=await this.auth.authorizationHeader();if(o.body!==undefined){headers["Content-Type"]="application/json"}if(o.idempotencyKey)headers["Idempotency-Key"]=o.idempotencyKey;let response:Response;try{response=await this.fetcher(this.url(path,o.params),{method,headers,body:o.body===undefined?undefined:JSON.stringify(o.body),signal:o.signal})}catch(e){if(this.retry.canRetry(method,attempt,!!o.idempotencyKey)){await this.sleep(this.retry.delay(attempt));continue}throw new NetworkError(`${method} ${path} failed before a response: ${String(e)}`,e)}this.lastResponseInfo=responseInfo(response);if(!response.ok&&this.retry.isRetryableStatus(response.status)&&this.retry.canRetry(method,attempt,!!o.idempotencyKey)){await this.sleep(this.retry.delay(attempt,parseRetryAfter(response.headers.get("Retry-After"))));continue}if(!response.ok)throw await mapError(response,o.idempotencyKey);return response}}
 async json<T>(method:string,path:string,o:RequestOptions={}):Promise<T>{const r=await this.request(method,path,o);try{return await r.json() as T}catch(e){throw new ApiError(`${method} ${path} returned a non-JSON ${r.status} response`,r.status,r.headers.get("X-Request-ID")??undefined,undefined)}}
 private url(path:string,params?:Record<string,string|number>){const u=new URL(path,this.baseUrl);for(const [k,v]of Object.entries(params??{}))u.searchParams.set(k,String(v));return u}
}
export class RunsResource {constructor(private c:MeemeeClient){} create(goal:string,o:{approveWrites?:boolean;signal?:AbortSignal}={}){goalCheck(goal);return this.c.json<RunReport>("POST","/v1/runs",{body:{goal,approve_writes:o.approveWrites??false},signal:o.signal})}}
export class JobsResource {
 constructor(private c:MeemeeClient){} create(goal:string,o:{runAt?:Date|string;idempotencyKey?:string}={}){goalCheck(goal);const body:{goal:string;run_at?:string}={goal};if(o.runAt)body.run_at=o.runAt instanceof Date?o.runAt.toISOString():o.runAt;return this.c.json<CreatedJob>("POST","/v1/jobs",{body,idempotencyKey:o.idempotencyKey})} get(id:string){return this.c.json<Job>("GET",`/v1/jobs/${encodeURIComponent(id)}`)} cancel(id:string){return this.c.json<JobCancelResult>("DELETE",`/v1/jobs/${encodeURIComponent(id)}`)} async events(id:string,after=0){return (await this.c.json<{events:JobEvent[]}>("GET",`/v1/jobs/${encodeURIComponent(id)}/events`,{params:{after}})).events}
 async *streamEvents(id:string,o:{after?:number;reconnect?:boolean;maxReconnects?:number;signal?:AbortSignal;onHeartbeat?:(s:string)=>void}={}):AsyncGenerator<JobEvent>{let cursor=Math.max(0,o.after??0),left=o.maxReconnects??6,backoff=1000;for(;;){const headers:Record<string,string>={Accept:"text/event-stream"};if(cursor)headers["Last-Event-ID"]=String(cursor);try{const r=await this.c.request("GET",`/v1/jobs/${encodeURIComponent(id)}/stream`,{params:{after:cursor},headers,signal:o.signal});if(!r.body)return;const parser=new SSEParser();for await(const chunk of streamChunks(r.body)){for(const m of parser.feed(chunk)){if(m.kind==="comment"){o.onHeartbeat?.(m.comment??"");continue}if(m.event==="error")throw new StreamError(`server sent an error frame on job ${id}: ${m.data}`);let event:JobEvent;try{event=JSON.parse(m.data??"") as JobEvent}catch(e){throw new StreamError(`malformed SSE data frame on job ${id}`)}if(typeof event.sequence!=="number"||event.job_id!==id)throw new StreamError(`unparseable job event on job ${id}`);cursor=Math.max(cursor,event.sequence);yield event;if(TERMINAL_EVENT_KINDS.has(event.kind))return}}return}catch(e){if(e instanceof ApiError||e instanceof StreamError||o.signal?.aborted)throw e;if(o.reconnect===false||left--<=0)throw new NetworkError(`job stream for ${id} interrupted (last delivered event id ${cursor})`,e);await new Promise(r=>setTimeout(r,backoff));backoff=Math.min(backoff*2,30000)}}}
 async wait(id:string,o:{timeoutMs?:number;pollIntervalMs?:number}={}){const interval=o.pollIntervalMs??2000;if(interval<=0)throw new TypeError("pollIntervalMs must be positive");const end=o.timeoutMs===undefined?Infinity:Date.now()+o.timeoutMs;for(;;){const job=await this.get(id);if(TERMINAL_JOB_STATUSES.has(job.status))return job;if(Date.now()>=end)throw new WaitTimeoutError(`job ${id} is still ${job.status} after ${o.timeoutMs}ms`);await new Promise(r=>setTimeout(r,Math.min(interval,end-Date.now())))}}
}
export class TokensResource {constructor(private c:MeemeeClient){}create(name:string,scopes:string[],expiresAt?:string){return this.c.json<CreatedToken>("POST","/v1/tokens",{body:{name,scopes,expires_at:expiresAt??null}})}revoke(id:string){return this.c.json<RevokedToken>("DELETE",`/v1/tokens/${encodeURIComponent(id)}`)}}
export class AuditResource {constructor(private c:MeemeeClient){}list(after=0,limit=100){return this.c.json<AuditPage>("GET","/v1/audit",{params:{after,limit}})}}
async function* streamChunks(body:ReadableStream<Uint8Array>){const reader=body.getReader();try{for(;;){const x=await reader.read();if(x.done)return;yield x.value}}finally{reader.releaseLock()}}
function goalCheck(g:string){if(!g.trim())throw new TypeError("goal must be a non-empty string")}
function parseRetryAfter(v:string|null):number|undefined{if(v===null)return undefined;const n=Number(v);if(Number.isFinite(n))return Math.max(0,n);const date=Date.parse(v);return Number.isNaN(date)?undefined:Math.max(0,(date-Date.now())/1000)}
function responseInfo(r:Response):ResponseInfo{const info:ResponseInfo={};const rid=r.headers.get("X-Request-ID");if(rid)info.requestId=rid;const limit=r.headers.get("RateLimit-Limit"),remaining=r.headers.get("RateLimit-Remaining"),reset=r.headers.get("RateLimit-Reset");if(limit||remaining||reset){const q:{limit?:number;remaining?:number;reset?:Date}={};if(limit)q.limit=Number(limit);if(remaining)q.remaining=Number(remaining);if(reset)q.reset=new Date(Number(reset)*1000);info.rateLimit=q}return info}
async function mapError(r:Response,key?:string):Promise<ApiError>{let detail:unknown;let bodyRid:unknown;try{const b=await r.clone().json() as {detail?:unknown;request_id?:unknown};detail=b.detail;bodyRid=b.request_id}catch{detail=(await r.text()).slice(0,500)||undefined}const rid=r.headers.get("X-Request-ID")??(typeof bodyRid==="string"?bodyRid:undefined);let text=typeof detail==="string"?detail:`HTTP ${r.status}`;if(Array.isArray(detail))text=detail.map(x=>typeof x==="object"&&x?String((x as {msg?:unknown}).msg??""):String(x)).join("; ");const msg=`HTTP ${r.status}: ${text}${rid?` (request_id=${rid})`:""}`;switch(r.status){case 400:return new BadRequestError(msg,400,rid,detail);case 401:return new AuthenticationError(msg,401,rid,detail,r.headers.get("WWW-Authenticate")??undefined);case 403:return new PermissionDeniedError(msg,403,rid,detail,typeof detail==="string"&&detail.startsWith("missing scope: ")?detail.slice(15).trim():undefined);case 404:return new NotFoundError(msg,404,rid,detail);case 409:return key?new IdempotencyConflictError(msg,409,rid,detail,key):new ConflictError(msg,409,rid,detail);case 422:return new ValidationError(msg,422,rid,detail,Array.isArray(detail)?detail as Record<string,unknown>[]:undefined);case 429:return new RateLimitError(msg,429,rid,detail,parseRetryAfter(r.headers.get("Retry-After")));default:return new ServerError(msg,r.status,rid,detail)}}
